name: Update NPM Dependencies (Create PR)

on:
  schedule:
    # Runs every Monday at 05:00 UTC
    - cron: '0 5 * * 1'
  workflow_dispatch: # Allows manual triggering

permissions:
  contents: write
  pull-requests: write

jobs:
  update-deps-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          # Updated to use the current LTS version
          node-version: '20' # Updated from '18' to '20'
          cache: 'npm'

      - name: Install Dependencies (Clean Slate)
        run: npm ci

      - name: Update Dependencies
        run: npm update

      # --- Optional but Recommended: Check if updates break build/tests ---
      - name: Build Project Check
        run: npm run build
      # - name: Run Tests Check
      #   run: npm test
      # -------------------------------------------------------------------

      - name: Create Package Updates PR
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          # Configure git
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          # Create a branch
          git checkout -b chore/npm-dependency-updates
          
          # Check if there are changes
          if ! git diff --quiet package.json package-lock.json; then
            # Commit changes
            git add package.json package-lock.json
            git commit -m "chore(deps): update npm dependencies"
            git push -f origin chore/npm-dependency-updates
            
            # Create PR without labels
            gh pr create --base main --head chore/npm-dependency-updates \
              --title "chore(deps): Update NPM dependencies" \
              --body "Automated dependency update via GitHub Actions.\n\nUpdates npm dependencies based on \`package.json\` constraints.\nPlease review changes and test thoroughly before merging."
          else
            echo "No dependency updates found."
          fi
        shell: bash
