name: Check & Propose Node.js LTS Update

on:
  schedule:
    # Runs on the 1st of every month at 06:00 UTC
    - cron: '0 6 1 * *'
  workflow_dispatch: # Allows manual triggering

permissions:
  contents: write
  pull-requests: write
  workflows: write # <<< ADD THIS LINE

jobs:
  propose-node-update:
    runs-on: ubuntu-latest
    outputs:
      latest_lts_major: ${{ steps.get_versions.outputs.latest_lts_major }}
      needs_update: ${{ steps.get_versions.outputs.needs_update }}
    steps:
      # ... rest of the steps remain the same ...

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get Latest LTS and Current Configured Node Version
        id: get_versions
        run: |
          echo "Fetching latest Node.js LTS version..."
          LATEST_LTS_VERSION=$(curl -s https://nodejs.org/dist/index.json | jq -r '[.[] | select(.lts != false)] | sort_by(.date) | reverse | .[0].version')
          LATEST_LTS_MAJOR=$(echo $LATEST_LTS_VERSION | sed 's/v\([0-9]*\).*/\1/')
          echo "Latest LTS Major: ${LATEST_LTS_MAJOR}"

          echo "Finding current Node version configured in primary workflow..."
          PRIMARY_WORKFLOW_FILE=".github/workflows/auto-dependency-deploy.yml" # CHECK THIS PATH
          CURRENT_NODE_LINE=$(grep -m 1 'node-version:' "$PRIMARY_WORKFLOW_FILE")
          CURRENT_MAJOR=$(echo "$CURRENT_NODE_LINE" | sed -n 's/.*node-version:[^0-9]*\([0-9]\+\).*/\1/p')

          if [[ -z "$CURRENT_MAJOR" ]]; then
            echo "Error: Could not find current major Node version in $PRIMARY_WORKFLOW_FILE"
            exit 1
          fi
          echo "Current Configured Major: ${CURRENT_MAJOR}"

          echo "latest_lts_major=${LATEST_LTS_MAJOR}" >> $GITHUB_OUTPUT
          echo "current_major=${CURRENT_MAJOR}" >> $GITHUB_OUTPUT

          if [[ "$LATEST_LTS_MAJOR" -gt "$CURRENT_MAJOR" ]]; then
            echo "Update needed."
            echo "needs_update=true" >> $GITHUB_OUTPUT
          else
            echo "No Node.js major version update needed."
            echo "needs_update=false" >> $GITHUB_OUTPUT
          fi
        shell: bash

      - name: Update node-version in ALL Workflow Files
        if: steps.get_versions.outputs.needs_update == 'true'
        run: |
          echo "Updating node-version to ${{ steps.get_versions.outputs.latest_lts_major }} in .github/workflows/*.yml"
          find .github/workflows -name '*.yml' -exec sed -i -E "s/(node-version:[[:space:]]*['\"]?)[0-9]+([\.\w]*['\"]?)/\1${{ steps.get_versions.outputs.latest_lts_major }}\2/" {} \;
          echo "--- Files Updated ---"
          git status --porcelain
          echo "---------------------"

      - name: Create Pull Request for Node.js Update (Requires Manual Review & flake.nix update)
        if: steps.get_versions.outputs.needs_update == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore(ci): propose Node.js v${{ steps.get_versions.outputs.latest_lts_major }} update in workflows"
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: chore/propose-node-version-${{ steps.get_versions.outputs.latest_lts_major }}
          delete-branch: true
          title: "chore(ci): Propose Node.js LTS v${{ steps.get_versions.outputs.latest_lts_major }} update for workflows"
          body: |
            Automated Node.js version update detected for workflows.

            Proposing update to `node-version` for latest LTS: **v${{ steps.get_versions.outputs.latest_lts_major }}**.

            **Manual Action Required Before Merging:**
            *   Review changes to `.github/workflows/*.yml` files.
            *   **Manually update `flake.nix`** (e.g., `pkgs.nodejs_XX`) to use Node.js **v${{ steps.get_versions.outputs.latest_lts_major }}**.
            *   Update other project files (`.nvmrc`, `package.json engines`) if needed.
            *   Test thoroughly after updating all locations.
            *   Merge this PR **after** updating `flake.nix` and testing.
          labels: dependencies,ci,automated pr,node-version,needs-manual-action