name: Check & Propose Node.js LTS Update

on:
  schedule:
    # Runs on the 1st of every month at 06:00 UTC
    - cron: '0 6 1 * *'
  workflow_dispatch: # Allows manual triggering

# Define permissions needed by the actions used in the workflow
# Relying on Repository Setting "Read and write permissions" for the ability
# for the token to push commits modifying *.yml files in .github/workflows/
permissions:
  contents: write         # Needed by checkout@v4 and create-pull-request@v6
  pull-requests: write    # Needed by create-pull-request@v6

jobs:
  propose-node-update:
    runs-on: ubuntu-latest
    outputs:
      latest_lts_major: ${{ steps.get_versions.outputs.latest_lts_major }}
      needs_update: ${{ steps.get_versions.outputs.needs_update }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get Latest LTS and Current Configured Node Version
        id: get_versions
        run: |
          echo "Fetching latest Node.js LTS version..."
          LATEST_LTS_VERSION=$(curl -s https://nodejs.org/dist/index.json | jq -r '[.[] | select(.lts != false)] | sort_by(.date) | reverse | .[0].version')
          LATEST_LTS_MAJOR=$(echo $LATEST_LTS_VERSION | sed 's/v\([0-9]*\).*/\1/')
          echo "Latest LTS Major: ${LATEST_LTS_MAJOR}"

          echo "Finding current Node version configured in primary workflow..."
          # IMPORTANT: Verify this path points to your MAIN workflow that defines the Node version
          PRIMARY_WORKFLOW_FILE=".github/workflows/auto-dependency-deploy.yml" # CHECK THIS PATH
          if [[ ! -f "$PRIMARY_WORKFLOW_FILE" ]]; then
             echo "Error: Primary workflow file not found at $PRIMARY_WORKFLOW_FILE"
             # Attempt to find *any* workflow using node-version as a fallback
             PRIMARY_WORKFLOW_FILE=$(grep -l -m 1 'node-version:' .github/workflows/*.yml | head -n 1)
             if [[ -z "$PRIMARY_WORKFLOW_FILE" ]]; then
                echo "Error: Could not find any workflow file defining node-version."
                exit 1
             fi
             echo "Warning: Using fallback workflow file: $PRIMARY_WORKFLOW_FILE"
          fi

          CURRENT_NODE_LINE=$(grep -m 1 'node-version:' "$PRIMARY_WORKFLOW_FILE")
          CURRENT_MAJOR=$(echo "$CURRENT_NODE_LINE" | sed -n 's/.*node-version:[^0-9]*\([0-9]\+\).*/\1/p')

          if [[ -z "$CURRENT_MAJOR" ]]; then
            echo "Error: Could not find current major Node version in $PRIMARY_WORKFLOW_FILE"
            exit 1
          fi
          echo "Current Configured Major: ${CURRENT_MAJOR}"

          echo "latest_lts_major=${LATEST_LTS_MAJOR}" >> $GITHUB_OUTPUT
          echo "current_major=${CURRENT_MAJOR}" >> $GITHUB_OUTPUT

          if [[ "$LATEST_LTS_MAJOR" -gt "$CURRENT_MAJOR" ]]; then
            echo "Update needed."
            echo "needs_update=true" >> $GITHUB_OUTPUT
          else
            echo "No Node.js major version update needed."
            echo "needs_update=false" >> $GITHUB_OUTPUT
          fi
        shell: bash

      - name: Update node-version in Target Workflow File(s) # Renamed for clarity
        if: steps.get_versions.outputs.needs_update == 'true'
        run: |
          LATEST_LTS_MAJOR="${{ steps.get_versions.outputs.latest_lts_major }}"
          echo "Updating node-version to ${LATEST_LTS_MAJOR} in .github/workflows/*.yml"
          # Use find and sed to modify the actual workflow files
          find .github/workflows -name '*.yml' -exec sed -i -E "s/(node-version:[[:space:]]*['\"]?)[0-9]+([\.\w]*['\"]?)/\1${LATEST_LTS_MAJOR}\2/" {} \;
          echo "--- Files Modified (if any) ---"
          # Show the changes that were actually made by sed
          git diff -- .github/workflows/
          echo "-------------------------------"
        shell: bash

      # Use peter-evans action to create PR from the modified files
      - name: Create Pull Request for Node.js Workflow Update
        if: steps.get_versions.outputs.needs_update == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # Commit message reflects the change made by the previous step
          commit-message: "chore(ci): update node-version to v${{ steps.get_versions.outputs.latest_lts_major }} in workflows"
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          # Branch name specific to the action taken
          branch: chore/update-workflow-node-version-${{ steps.get_versions.outputs.latest_lts_major }}
          delete-branch: true
          # Title reflects the actual change
          title: "chore(ci): Update Node.js to LTS v${{ steps.get_versions.outputs.latest_lts_major }} in workflows"
          # Body explains the change and required manual steps
          body: |
            Automated Node.js version update detected for workflows.

            This PR updates the `node-version` to the latest LTS: **v${{ steps.get_versions.outputs.latest_lts_major }}** in relevant workflow files.

            **Manual Action Required Before Merging:**
            *   Review changes to `.github/workflows/*.yml` files made in this PR's commit.
            *   **Manually update `flake.nix`** (e.g., `pkgs.nodejs_XX`) to use Node.js **v${{ steps.get_versions.outputs.latest_lts_major }}**.
            *   Update other project files (`.nvmrc`, `package.json engines`) if needed.
            *   Test thoroughly after updating all locations.
            *   Merge this PR **after** updating `flake.nix` and testing.
          labels: dependencies,ci,automated pr,node-version,needs-manual-action